laser_node:
  ros__parameters:
    product_name: LDLiDAR_LD06
    laser_scan_topic_name: scan
    point_cloud_2d_topic_name: ''
    frame_id: laser_frame
    port_name: /dev/ttyLIDAR
    serial_baudrate: 230400
    laser_scan_dir: true
    enable_angle_crop_func: false
    angle_crop_min: 135.0  # degrees
    angle_crop_max: 225.0  # degrees
    range_min: 0.02  # meters
    range_max: 12.0  # meters
