image_width: 640
image_height: 480
camera_name: webcam_node
camera_matrix:
  rows: 3
  cols: 3
  data:
  - 719.9532032048179
  - 0.0
  - 341.729237923363
  - 0.0
  - 720.5131653458442
  - 194.1066634964482
  - 0.0
  - 0.0
  - 1.0
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 14
  data:
  - -27.033964369621696
  - 259.86005026725906
  - -0.002374964365094848
  - 0.008202497340645187
  - 89.29583313290841
  - -27.00915544542908
  - 259.0612549325502
  - 101.24193740775492
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
rectification_matrix:
  rows: 3
  cols: 3
  data:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
projection_matrix:
  rows: 3
  cols: 4
  data:
  - 719.9532032048179
  - 0.0
  - 341.729237923363
  - 0.0
  - 0.0
  - 720.5131653458442
  - 194.1066634964482
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
