teleop_twist_joy:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick vertical
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0  # Left stick horizontal
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 4  # L1 button
    enable_turbo_button: 5  # R1 button

    require_enable_button: true
